language: c

python:
    - 3.5

os: 
    - linux
    - osx

notifications:
  email: false

git:
  depth: 3

install: 
    - cd build
    - CC=$COMP cmake ../src
    - make
    - cd ..

script:
    - python tests/test.py

